#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : WireGuard
Version  : 0.0.20190123
Release  : 3
URL      : https://git.zx2c4.com/WireGuard/snapshot/WireGuard-0.0.20190123.tar.xz
Source0  : https://git.zx2c4.com/WireGuard/snapshot/WireGuard-0.0.20190123.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: WireGuard-bin
Requires: WireGuard-config
Requires: WireGuard-data
Requires: WireGuard-license
Requires: WireGuard-man
BuildRequires : buildreq-golang
BuildRequires : libmnl-dev

%description
These scripts should be modified according to your precise setup.
They provide a very simple way of tunneling synergy inside of a
WireGuard tunnel, to protect your data in transit.

%package bin
Summary: bin components for the WireGuard package.
Group: Binaries
Requires: WireGuard-data
Requires: WireGuard-config
Requires: WireGuard-license
Requires: WireGuard-man

%description bin
bin components for the WireGuard package.


%package config
Summary: config components for the WireGuard package.
Group: Default

%description config
config components for the WireGuard package.


%package data
Summary: data components for the WireGuard package.
Group: Data

%description data
data components for the WireGuard package.


%package license
Summary: license components for the WireGuard package.
Group: Default

%description license
license components for the WireGuard package.


%package man
Summary: man components for the WireGuard package.
Group: Default

%description man
man components for the WireGuard package.


%prep
%setup -q -n WireGuard-0.0.20190123

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533332596
pushd src/tools
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1533332596
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/WireGuard
cp COPYING %{buildroot}/usr/share/doc/WireGuard/COPYING
pushd src/tools
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wg
/usr/bin/wg-quick

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/wg-quick@.service

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/wg
/usr/share/bash-completion/completions/wg-quick

%files license
%defattr(-,root,root,-)
/usr/share/doc/WireGuard/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/wg-quick.8
/usr/share/man/man8/wg.8
